# Generated by Django 5.2 on 2025-05-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
