# Generated by Django 5.2 on 2025-05-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0002_flow_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="role",
            field=models.CharField(
                choices=[
                    ("business_ops", "Business & Operations"),
                    ("sales_cs", "Sales & Customer Success"),
                    ("marketing_growth", "Marketing & Growth"),
                    ("product_design", "Product & Design"),
                    ("engineering_data", "Engineering & Data"),
                    ("people_hr", "People & HR"),
                    ("finance_legal", "Finance & Legal"),
                    ("support_services", "Support & Services"),
                    ("science_research", "Science & Research"),
                    ("executive_leadership", "Executive & Leadership"),
                ],
                default="business_ops",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
