# Generated by Django 5.2 on 2025-05-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0003_flow_role"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="candidate",
            unique_together={("email", "flow")},
        ),
    ]
