# Generated by Django 5.2 on 2025-05-06 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0005_flow_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flow",
            name="description",
        ),
        migrations.RemoveField(
            model_name="flow",
            name="name",
        ),
        migrations.AddField(
            model_name="candidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("complete", "Complete"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="flow",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="interviews.flow",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="step",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("coding", "Coding Challenge"),
                    ("system_design", "System Design"),
                    ("behavioral", "Behavioral"),
                    ("technical", "Technical Discussion"),
                    ("behavioral", "Behavioral"),
                    ("coding", "Coding Challenge"),
                ],
                max_length=20,
            ),
        ),
    ]
