# Generated by Django 5.2 on 2025-05-06 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0007_add_role_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BehavioralStep",
            fields=[
                (
                    "step_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="interviews.step",
                    ),
                ),
                ("behavioral_areas", models.JSONField(default=list)),
                ("custom_questions", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "Behavioral Step",
                "verbose_name_plural": "Behavioral Steps",
            },
            bases=("interviews.step",),
        ),
        migrations.CreateModel(
            name="ProjectStep",
            fields=[
                (
                    "step_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="interviews.step",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("instructions", models.TextField()),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Document"),
                            ("zip", "ZIP Archive"),
                            ("github", "GitHub Repository"),
                            ("doc", "Word Document"),
                            ("other", "Other Format"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Step",
                "verbose_name_plural": "Project Steps",
            },
            bases=("interviews.step",),
        ),
        migrations.CreateModel(
            name="TechnicalStep",
            fields=[
                (
                    "step_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="interviews.step",
                    ),
                ),
                ("technical_areas", models.JSONField(default=list)),
                ("custom_questions", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "Technical Step",
                "verbose_name_plural": "Technical Steps",
            },
            bases=("interviews.step",),
        ),
        migrations.AlterField(
            model_name="step",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("technical", "Technical"),
                    ("behavioral", "Behavioral"),
                    ("project", "Project"),
                ],
                max_length=20,
            ),
        ),
    ]
