# Generated by Django 5.2 on 2025-05-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0008_behavioralstep_projectstep_technicalstep_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="interviewer_tone",
            field=models.CharField(
                choices=[
                    ("friendly", "Friendly & Supportive"),
                    ("professional", "Professional & Neutral"),
                    ("challenging", "Challenging & High-Bar"),
                    ("casual", "Casual & Conversational"),
                ],
                default="professional",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="technicalstep",
            name="time_limit",
            field=models.IntegerField(default=30),
        ),
    ]
