# Generated by Django 5.2 on 2025-05-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0009_step_interviewer_tone_technicalstep_time_limit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="behavioralstep",
            name="custom_questions",
        ),
        migrations.RemoveField(
            model_name="behavioralstep",
            name="behavioral_areas",
        ),
        migrations.RemoveField(
            model_name="technicalstep",
            name="technical_areas",
        ),
        migrations.RemoveField(
            model_name="technicalstep",
            name="custom_questions",
        ),
        migrations.RemoveField(
            model_name="technicalstep",
            name="time_limit",
        ),
        migrations.AddField(
            model_name="step",
            name="assessed_skills",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="step",
            name="custom_questions",
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name="BehavioralStep",
        ),
        migrations.DeleteModel(
            name="TechnicalStep",
        ),
    ]
