# Generated by Django 5.2 on 2025-05-06 17:26

from django.db import migrations, models

import interviews.storage


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0010_remove_behavioral_technical_steps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="resume_url",
        ),
        migrations.AddField(
            model_name="candidate",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                storage=interviews.storage.CandidateResumeStorage(),
                upload_to="resumes",
            ),
        ),
    ]
