# Generated by Django 5.2 on 2025-05-06 17:30

from django.db import migrations, models

import interviews.storage


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0011_remove_candidate_resume_url_candidate_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                storage=interviews.storage.CandidateResumeStorage(),
                upload_to="",
            ),
        ),
    ]
