# Generated by Django 4.2.11 on 2025-05-06 18:39

from django.db import migrations, models

import interviews.models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0012_alter_candidate_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=interviews.models.CandidateProfilePictureStorage(),
                upload_to="profile_pictures/",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                storage=interviews.models.CandidateResumeStorage(),
                upload_to="",
            ),
        ),
    ]
