# Generated by Django 4.2.11 on 2025-05-06 18:42

from django.db import migrations, models

import interviews.storage


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0013_candidate_profile_picture_alter_candidate_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=interviews.storage.CandidateProfilePictureStorage(),
                upload_to="",
            ),
        ),
    ]
