# Generated by Django 4.2.11 on 2025-05-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0014_alter_candidate_profile_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "companies"},
        ),
        migrations.AddField(
            model_name="recruiter",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
